language: php

sudo: false

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - SYMFONY_VERSION="2.1.*"
    - SYMFONY_VERSION="2.2.*"
    - SYMFONY_VERSION="2.3.*"

before_script:
    - composer self-update -q
    - composer require --no-update symfony/framework-bundle:${SYMFONY_VERSION}
    - composer install --dev --prefer-source

script: bin/phpunit

notifications:
    email: benjamin.lazarecki@gmail.com
